# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: avatica.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import requests_pb2 as requests__pb2
import responses_pb2 as responses__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='avatica.proto',
  package='phoenixdb',
  syntax='proto3',
  serialized_pb=_b('\n\ravatica.proto\x12\tphoenixdb\x1a\x0erequests.proto\x1a\x0fresponses.proto2\xfe\n\n\x07\x41vatica\x12\x46\n\x08\x43\x61talogs\x12\x1a.phoenixdb.CatalogsRequest\x1a\x1c.phoenixdb.ResultSetResponse\"\x00\x12Z\n\x0f\x43loseConnection\x12!.phoenixdb.CloseConnectionRequest\x1a\".phoenixdb.CloseConnectionResponse\"\x00\x12W\n\x0e\x43loseStatement\x12 .phoenixdb.CloseStatementRequest\x1a!.phoenixdb.CloseStatementResponse\"\x00\x12\x44\n\x07\x43olumns\x12\x19.phoenixdb.ColumnsRequest\x1a\x1c.phoenixdb.ResultSetResponse\"\x00\x12\x42\n\x06\x43ommit\x12\x18.phoenixdb.CommitRequest\x1a\x1c.phoenixdb.ResultSetResponse\"\x00\x12W\n\x0e\x43onnectionSync\x12 .phoenixdb.ConnectionSyncRequest\x1a!.phoenixdb.ConnectionSyncResponse\"\x00\x12Z\n\x0f\x43reateStatement\x12!.phoenixdb.CreateStatementRequest\x1a\".phoenixdb.CreateStatementResponse\"\x00\x12]\n\x10\x44\x61tabaseProperty\x12\".phoenixdb.DatabasePropertyRequest\x1a#.phoenixdb.DatabasePropertyResponse\"\x00\x12\x42\n\x07\x45xecute\x12\x19.phoenixdb.ExecuteRequest\x1a\x1a.phoenixdb.ExecuteResponse\"\x00\x12<\n\x05\x46\x65tch\x12\x17.phoenixdb.FetchRequest\x1a\x18.phoenixdb.FetchResponse\"\x00\x12W\n\x0eOpenConnection\x12 .phoenixdb.OpenConnectionRequest\x1a!.phoenixdb.OpenConnectionResponse\"\x00\x12V\n\x11PrepareAndExecute\x12#.phoenixdb.PrepareAndExecuteRequest\x1a\x1a.phoenixdb.ExecuteResponse\"\x00\x12\x42\n\x07Prepare\x12\x19.phoenixdb.PrepareRequest\x1a\x1a.phoenixdb.PrepareResponse\"\x00\x12\x45\n\x08Rollback\x12\x1a.phoenixdb.RollbackRequest\x1a\x1b.phoenixdb.RollbackResponse\"\x00\x12\x44\n\x07Schemas\x12\x19.phoenixdb.SchemasRequest\x1a\x1c.phoenixdb.ResultSetResponse\"\x00\x12\x42\n\x06Tables\x12\x18.phoenixdb.TablesRequest\x1a\x1c.phoenixdb.ResultSetResponse\"\x00\x12H\n\nTableTypes\x12\x1a.phoenixdb.TypeInfoRequest\x1a\x1c.phoenixdb.ResultSetResponse\"\x00\x12\x46\n\x08TypeInfo\x12\x1a.phoenixdb.TypeInfoRequest\x1a\x1c.phoenixdb.ResultSetResponse\"\x00\x42\x03\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[requests__pb2.DESCRIPTOR,responses__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_AVATICA = _descriptor.ServiceDescriptor(
  name='Avatica',
  full_name='phoenixdb.Avatica',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=62,
  serialized_end=1468,
  methods=[
  _descriptor.MethodDescriptor(
    name='Catalogs',
    full_name='phoenixdb.Avatica.Catalogs',
    index=0,
    containing_service=None,
    input_type=requests__pb2._CATALOGSREQUEST,
    output_type=responses__pb2._RESULTSETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseConnection',
    full_name='phoenixdb.Avatica.CloseConnection',
    index=1,
    containing_service=None,
    input_type=requests__pb2._CLOSECONNECTIONREQUEST,
    output_type=responses__pb2._CLOSECONNECTIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseStatement',
    full_name='phoenixdb.Avatica.CloseStatement',
    index=2,
    containing_service=None,
    input_type=requests__pb2._CLOSESTATEMENTREQUEST,
    output_type=responses__pb2._CLOSESTATEMENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Columns',
    full_name='phoenixdb.Avatica.Columns',
    index=3,
    containing_service=None,
    input_type=requests__pb2._COLUMNSREQUEST,
    output_type=responses__pb2._RESULTSETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Commit',
    full_name='phoenixdb.Avatica.Commit',
    index=4,
    containing_service=None,
    input_type=requests__pb2._COMMITREQUEST,
    output_type=responses__pb2._RESULTSETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectionSync',
    full_name='phoenixdb.Avatica.ConnectionSync',
    index=5,
    containing_service=None,
    input_type=requests__pb2._CONNECTIONSYNCREQUEST,
    output_type=responses__pb2._CONNECTIONSYNCRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateStatement',
    full_name='phoenixdb.Avatica.CreateStatement',
    index=6,
    containing_service=None,
    input_type=requests__pb2._CREATESTATEMENTREQUEST,
    output_type=responses__pb2._CREATESTATEMENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DatabaseProperty',
    full_name='phoenixdb.Avatica.DatabaseProperty',
    index=7,
    containing_service=None,
    input_type=requests__pb2._DATABASEPROPERTYREQUEST,
    output_type=responses__pb2._DATABASEPROPERTYRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='phoenixdb.Avatica.Execute',
    index=8,
    containing_service=None,
    input_type=requests__pb2._EXECUTEREQUEST,
    output_type=responses__pb2._EXECUTERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Fetch',
    full_name='phoenixdb.Avatica.Fetch',
    index=9,
    containing_service=None,
    input_type=requests__pb2._FETCHREQUEST,
    output_type=responses__pb2._FETCHRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OpenConnection',
    full_name='phoenixdb.Avatica.OpenConnection',
    index=10,
    containing_service=None,
    input_type=requests__pb2._OPENCONNECTIONREQUEST,
    output_type=responses__pb2._OPENCONNECTIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PrepareAndExecute',
    full_name='phoenixdb.Avatica.PrepareAndExecute',
    index=11,
    containing_service=None,
    input_type=requests__pb2._PREPAREANDEXECUTEREQUEST,
    output_type=responses__pb2._EXECUTERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Prepare',
    full_name='phoenixdb.Avatica.Prepare',
    index=12,
    containing_service=None,
    input_type=requests__pb2._PREPAREREQUEST,
    output_type=responses__pb2._PREPARERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Rollback',
    full_name='phoenixdb.Avatica.Rollback',
    index=13,
    containing_service=None,
    input_type=requests__pb2._ROLLBACKREQUEST,
    output_type=responses__pb2._ROLLBACKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Schemas',
    full_name='phoenixdb.Avatica.Schemas',
    index=14,
    containing_service=None,
    input_type=requests__pb2._SCHEMASREQUEST,
    output_type=responses__pb2._RESULTSETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Tables',
    full_name='phoenixdb.Avatica.Tables',
    index=15,
    containing_service=None,
    input_type=requests__pb2._TABLESREQUEST,
    output_type=responses__pb2._RESULTSETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TableTypes',
    full_name='phoenixdb.Avatica.TableTypes',
    index=16,
    containing_service=None,
    input_type=requests__pb2._TYPEINFOREQUEST,
    output_type=responses__pb2._RESULTSETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TypeInfo',
    full_name='phoenixdb.Avatica.TypeInfo',
    index=17,
    containing_service=None,
    input_type=requests__pb2._TYPEINFOREQUEST,
    output_type=responses__pb2._RESULTSETRESPONSE,
    options=None,
  ),
])

Avatica = service_reflection.GeneratedServiceType('Avatica', (_service.Service,), dict(
  DESCRIPTOR = _AVATICA,
  __module__ = 'avatica_pb2'
  ))

Avatica_Stub = service_reflection.GeneratedServiceStubType('Avatica_Stub', (Avatica,), dict(
  DESCRIPTOR = _AVATICA,
  __module__ = 'avatica_pb2'
  ))


# @@protoc_insertion_point(module_scope)
